// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt1hYHOfebmU9zEyxxThcwKCRqaEV1Qy8',
    appId: '1:93773023310:web:19cbf1a70d81cd1aa55b1f',
    messagingSenderId: '93773023310',
    projectId: 'happybash-kw',
    authDomain: 'happybash-kw.firebaseapp.com',
    storageBucket: 'happybash-kw.firebasestorage.app',
    measurementId: 'G-Y2JG6VEJZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGLW1bZc2rttuvjwwQs04ehnyfAWyZflw',
    appId: '1:93773023310:android:82fe90a207f3c57ea55b1f',
    messagingSenderId: '93773023310',
    projectId: 'happybash-kw',
    storageBucket: 'happybash-kw.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1EtM6gapyhRyOclnsTGRZI-LNmChwt8E',
    appId: '1:93773023310:ios:9dd83fe6a8277cd2a55b1f',
    messagingSenderId: '93773023310',
    projectId: 'happybash-kw',
    storageBucket: 'happybash-kw.firebasestorage.app',
    androidClientId: '93773023310-31irm3f62qil1c1pa7ulr8p536sldftp.apps.googleusercontent.com',
    iosClientId: '93773023310-ih7di816kfdb94e143jofjf2etv3audg.apps.googleusercontent.com',
    iosBundleId: 'com.happybash.main',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1EtM6gapyhRyOclnsTGRZI-LNmChwt8E',
    appId: '1:93773023310:ios:f3df85be75c382eda55b1f',
    messagingSenderId: '93773023310',
    projectId: 'happybash-kw',
    storageBucket: 'happybash-kw.firebasestorage.app',
    androidClientId: '93773023310-31irm3f62qil1c1pa7ulr8p536sldftp.apps.googleusercontent.com',
    iosClientId: '93773023310-419qive76550bdpkvoctmm45db7mq2sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.happyBash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt1hYHOfebmU9zEyxxThcwKCRqaEV1Qy8',
    appId: '1:93773023310:web:6aaa670b4f15af2ea55b1f',
    messagingSenderId: '93773023310',
    projectId: 'happybash-kw',
    authDomain: 'happybash-kw.firebaseapp.com',
    storageBucket: 'happybash-kw.firebasestorage.app',
    measurementId: 'G-YWG7FPZEYR',
  );

}